name: build cryptomator apk

on:
  push:    
  pull_request:
  workflow_dispatch:

env:
  CRYPTOMATOR_VERSION: "1.12.3"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout builder
        uses: actions/checkout@v5
        with:
          path: cryptomator-builder

      - name: build podman images
        working-directory: cryptomator-builder
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends podman
          podman build --target builder -t cryptomator-android-builder .
          podman build --target signer -t cryptomator-android-signer .

      - name: config environments
        run: |
          # Build environment (No signing keys)
          {
            echo "DROPBOX_API_KEY=${{ secrets.DROPBOX_API_KEY }}"
            echo "ONEDRIVE_API_KEY=${{ secrets.ONEDRIVE_API_KEY }}"
            echo "ONEDRIVE_API_REDIRCT_URI=${{ secrets.ONEDRIVE_API_REDIRCT_URI }}"
            echo "PCLOUD_CLIENT_ID=${{ secrets.PCLOUD_CLIENT_ID }}"
          } >> "${{ runner.temp }}/.env.build"

          # Sign environment (Only signing keys)
          {
            echo "SIGNING_KEYSTORE_PASSWORD=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}"
            echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}"
            echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}"
          } >> "${{ runner.temp }}/.env.sign"

          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > "${{ runner.temp }}/release.p12"

      - name: checkout cryptomator
        uses: actions/checkout@v5
        with:
          repository: cryptomator/android
          ref: ${{ env.CRYPTOMATOR_VERSION }}
          path: cryptomator-android

      - name: apply patches
        working-directory: cryptomator-android
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git am --3way ../cryptomator-builder/patches/*.patch

      - name: build apk
        run: |
          mkdir -p artifacts
          podman run \
            -v ./cryptomator-android:/build/cryptomator-android \
            -v ./artifacts:/build/artifacts \
            --env-file "${{ runner.temp }}/.env.build" \
            -e GIT_CONFIG_COUNT=1 \
            -e GIT_CONFIG_KEY_0=safe.directory \
            -e GIT_CONFIG_VALUE_0=* \
            cryptomator-android-builder \
            apkstore

      - name: sign apk
        run: |
          podman run \
            -v "${{ runner.temp }}/release.p12":/build/release.p12:ro \
            -v ./artifacts:/build/artifacts \
            --env-file "${{ runner.temp }}/.env.sign" \
            cryptomator-android-signer

      - name: prepare release
        env:
          CRYPTOMATOR_VERSION: ${{ env.CRYPTOMATOR_VERSION }}
          ES256_PRIVATE_KEY: ${{ secrets.ES256_PRIVATE_KEY }}
        run: |
          mkdir -p release
          cp ./artifacts/cryptomator-apkstore.apk ./release/cryptomator.apk

          npm install jsonwebtoken
          node << 'EOF'
            const fs = require('fs');
            const crypto = require('crypto');
            const jwt = require('jsonwebtoken');

            const CRYPTOMATOR_VERSION = process.env.CRYPTOMATOR_VERSION;
            const ES256_PRIVATE_KEY = process.env.ES256_PRIVATE_KEY;

            const fileBuffer = fs.readFileSync('./release/cryptomator.apk');
            const apkHash = crypto.createHash('sha256').update(fileBuffer).digest('hex');

            const payload = {
              version: CRYPTOMATOR_VERSION,
              url: `https://github.com/ObjectAscended/cryptomator-android/releases/download/${CRYPTOMATOR_VERSION}/cryptomator.apk`,
              apk_sha_256: apkHash,
              release_notes: `https://static.cryptomator.org/android/${CRYPTOMATOR_VERSION}/release-notes.html`
            };
            
            const token = jwt.sign(payload, ES256_PRIVATE_KEY, { algorithm: 'ES256' });

            fs.writeFileSync('./release/version.jwt', token);
          EOF

      - name: create release
        uses: softprops/action-gh-release@v2
        if: github.event_name != 'pull_request'
        with:
          tag_name: ${{ env.CRYPTOMATOR_VERSION }}
          files: |
            ./release/*